[package]

name = "legend_of_link"
version = "0.0.1"
authors = ["Nathaniel Theis <nttheis@gmail.com>"]

[dependencies.html5ever]
git = "https://github.com/servo/html5ever"

[dependencies.url]
git = "https://github.com/servo/rust-url"
